/*
 * WARNING: This file is autogenerated using the scripts/generate-rulesets.js
 * script. Do not edit manually.
 */

module.exports = Object.freeze({
  rules: {
    'code-complexity': ['warn', 7],
    'explicit-types': ['warn', 'explicit'],
    'function-max-lines': ['warn', 50],
    'interface-starts-with-i': 'warn',
    'max-line-length': ['error', 120],
    'max-states-count': ['warn', 15],
    'no-console': 'error',
    'no-empty-blocks': 'warn',
    'no-global-import': 'warn',
    'no-unused-import': 'warn',
    'no-unused-vars': 'warn',
    'one-contract-per-file': 'warn',
    'payable-fallback': 'warn',
    'reason-string': [
      'warn',
      {
        maxLength: 32,
      },
    ],
    'use-natspec': [
      'warn',
      {
        title: {
          enabled: true,
          ignore: {},
        },
        author: {
          enabled: true,
          ignore: {},
        },
        notice: {
          enabled: true,
          ignore: {},
        },
        param: {
          enabled: true,
          ignore: {},
        },
        return: {
          enabled: true,
          ignore: {},
        },
      },
    ],
    'constructor-syntax': 'warn',
    'gas-calldata-parameters': 'warn',
    'gas-custom-errors': 'warn',
    'gas-increment-by-one': 'warn',
    'gas-indexed-events': 'warn',
    'gas-length-in-loops': 'warn',
    'gas-multitoken1155': 'warn',
    'gas-named-return-values': 'warn',
    'gas-small-strings': 'warn',
    'gas-strict-inequalities': 'warn',
    'gas-struct-packing': 'warn',
    'comprehensive-interface': 'warn',
    'duplicated-imports': 'warn',
    'import-path-check': ['warn', ['[~dependenciesPath]']],
    quotes: ['error', 'double'],
    'const-name-snakecase': 'warn',
    'contract-name-capwords': 'warn',
    'event-name-capwords': 'warn',
    'foundry-test-functions': ['warn', ['setUp']],
    'func-name-mixedcase': 'warn',
    'func-named-parameters': ['warn', 4],
    'func-param-name-mixedcase': 'warn',
    'immutable-vars-naming': [
      'warn',
      {
        immutablesAsConstants: true,
      },
    ],
    'modifier-name-mixedcase': 'warn',
    'named-parameters-mapping': 'warn',
    'private-vars-leading-underscore': [
      'warn',
      {
        strict: false,
      },
    ],
    'use-forbidden-name': 'warn',
    'var-name-mixedcase': [
      'warn',
      {
        prefixForImmutables: 'IMM_',
      },
    ],
    'imports-on-top': 'warn',
    'imports-order': 'warn',
    ordering: 'warn',
    'visibility-modifier-order': 'warn',
    'avoid-call-value': 'warn',
    'avoid-low-level-calls': 'warn',
    'avoid-sha3': 'warn',
    'avoid-suicide': 'warn',
    'avoid-throw': 'warn',
    'avoid-tx-origin': 'warn',
    'check-send-result': 'warn',
    'compiler-version': ['error', '^0.8.24'],
    'func-visibility': [
      'warn',
      {
        ignoreConstructors: false,
      },
    ],
    'multiple-sends': 'warn',
    'no-complex-fallback': 'warn',
    'no-inline-assembly': 'warn',
    'not-rely-on-block-hash': 'warn',
    'not-rely-on-time': 'warn',
    reentrancy: 'warn',
    'state-visibility': 'warn',
  },
})
